version: '3'

services:
  app:
    container_name: Hoze
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:3000"
    volumes:
      - .:/app   # Montar el directorio actual en /app dentro del contenedor